# ⏰ Guia Completo do Tipo `datetime` em Python

## 📖 O que é `datetime`?

A classe `datetime` é um tipo de dado que representa **uma data e hora específicas** em Python.
Ela permite manipular:

* Ano, mês, dia
* Hora, minuto, segundo, microssegundo
* Dias da semana (segunda, terça, etc.)

A classe `datetime` faz parte do módulo **`datetime`**, que é padrão do Python e essencial para manipulação de datas e horários, cálculos de diferenças entre datas e formatação em diferentes padrões.

Em **análises de dados**, ela é muito usada para trabalhar com **séries temporais**.

---

## 🐼 `datetime` com Pandas

Com **Pandas**, podemos:

* Converter strings em objetos `datetime`
* Filtrar dados por intervalos de tempo
* Agregar dados por hora, dia, mês ou ano
* Realizar operações temporais de forma eficiente dentro de DataFrames

Exemplo prático:

```python
import pandas as pd

# criando um DataFrame com datas em string
df = pd.DataFrame({
    "data": ["2022-01-01", "2022-01-02", "2022-01-03"],
    "vendas": [100, 150, 200]
})

# convertendo para datetime
df['data'] = pd.to_datetime(df['data'])

# filtrando vendas após 2022-01-01
df_filtrado = df[df['data'] > '2022-01-01']
print(df_filtrado)
```

---

## 📚 Biblioteca `datetime` do Python

A biblioteca **`datetime`** fornece classes para trabalhar com datas e horas.

### 1️⃣ Criando um objeto `datetime` com a data e hora atual

```python
import datetime

# criando um objeto datetime com a data e hora atual
agora = datetime.datetime.now()

print("Data e hora atual:", agora)
```

* **`datetime.datetime.now()`** retorna um objeto `datetime` com **data e hora atual**.

---

### 2️⃣ Criando um objeto `date` com apenas a data

```python
import datetime

# criando um objeto date com a data de hoje
hoje = datetime.date.today()

print("Data de hoje:", hoje)
```

* **`datetime.date.today()`** retorna um objeto com **apenas a data atual**.

---

### 3️⃣ Operações matemáticas com datas

Você pode **calcular diferenças entre datas**:

```python
import datetime

# criando dois objetos date
data_1 = datetime.date(2022, 1, 1)
data_2 = datetime.date(2023, 1, 1)

# diferença entre datas
diferenca = data_2 - data_1

print("Diferença entre as datas:", diferenca)
```

* Resultado: `365 days` (diferença entre `data_2` e `data_1`)

Você também pode somar ou subtrair **`timedelta`** para manipular datas.

---

## 🔗 Recursos para se aprofundar

* Artigo: [Python datetime: Como definir data e hora em Python](https://www.geeksforgeeks.org/python-datetime/)
* Documentação oficial: [Python `datetime` module](https://docs.python.org/3/library/datetime.html)

---

In [1]:
import io
import pandas as pd
import  numpy as np

# URL do arquivo JSON contendo os dados de hospedagem
url = 'https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/moveis_disponiveis.json'

# Lê o arquivo JSON da URL
# Utiliza io.StringIO para tratar a URL como um arquivo em memória
# Converte o JSON lido para DataFrame, depois para JSON string
# e lê novamente para garantir o formato correto
dt_data = pd.read_json(io.StringIO(pd.read_json(url).to_json()))
dt_data.head()

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None
3  857  2016-01-07            False  None
4  857  2016-01-08            False  None

Temos quatro colunas: id, data, vaga_disponivel e preco. Dentre elas, aquela que mais nos interessa é a data.

Vemos que ela possui o formato "ano-mês-dia" (AAAA-MM-DD). Este é um formato padrão da estrutura do datetime

In [2]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

O Pandas fornece o método to_datetime() que nos permite transformar a coluna de um dataframe em datetime.

In [3]:
pd.to_datetime(dt_data['data'])

0        2016-01-04
1        2016-01-05
2        2016-01-06
3        2016-01-07
4        2016-01-08
            ...
364995   2016-12-29
364996   2016-12-30
364997   2016-12-31
364998   2017-01-01
364999   2017-01-02
Name: data, Length: 365000, dtype: datetime64[ns]

O formato deixou de ser object e passou a ser datetime64, portanto, conseguimos converter esses dados com o método to_datetime().

In [4]:
dt_data['data'] = pd.to_datetime(dt_data['data'])

In [5]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

#Manipulando dados temporais

In [6]:
dt_data.head()

    id       data  vaga_disponivel preco
0  857 2016-01-04            False  None
1  857 2016-01-05            False  None
2  857 2016-01-06            False  None
3  857 2016-01-07            False  None
4  857 2016-01-08            False  None

`strftime()`

In [7]:
#formatação do tempo
dt_data['data'].dt.strftime('%Y-%m') #y = year, m = month

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: object

### Agrupando vagas por mês com `groupby`

Nosso objetivo é **agrupar os dados por mês** e calcular **quantas vagas estavam disponíveis em cada mês**. Para isso, usamos o método `groupby` do Pandas.

#### Passo a passo:

1. **Criar o agrupamento por mês**
   Usamos a coluna `data` para extrair o ano e o mês de cada registro. Com isso, todas as linhas do mesmo mês serão agrupadas:

```python
dt_data['data'].dt.strftime('%Y-%m')
```

2. **Aplicar o `groupby`**
   Passamos a seleção de "ano–mês" para dentro do `groupby()` e selecionamos a coluna `vaga_disponivel`:

```python
dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel']
```

3. **Somar os valores booleanos**
   Como a coluna `vaga_disponivel` contém valores booleanos (`True` ou `False`), o Python trata:

* `True` → 1
* `False` → 0

Assim, a função `sum()` contará **quantos dias houve vagas disponíveis** em cada mês:

```python
dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
```

4. **Resultado**
   O resultado será uma tabela com cada mês e a soma de vagas disponíveis naquele período. Por exemplo:

| data    | vaga\_disponivel |
| ------- | ---------------- |
| 2016-01 | 16543            |
| 2016-02 | 20128            |
| 2016-03 | 23357            |
| ...     | ...              |

🔹 **Interpretação:** Cada número indica **quantos dias naquele mês tinham vagas disponíveis**.

In [8]:
dt_data[dt_data['vaga_disponivel'] == True]

          id       data  vaga_disponivel    preco
56       857 2016-02-29             True  $120.00
57       857 2016-03-01             True  $120.00
58       857 2016-03-02             True  $120.00
59       857 2016-03-03             True  $120.00
60       857 2016-03-04             True  $120.00
...      ...        ...              ...      ...
364994  3279 2016-12-28             True  $140.00
364995  3279 2016-12-29             True  $140.00
364996  3279 2016-12-30             True  $140.00
364997  3279 2016-12-31             True  $140.00
364998  3279 2017-01-01             True  $140.00

[270547 rows x 4 columns]

In [9]:
# Agrupa os dados por ano e mês e soma a disponibilidade de vagas
dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [10]:
subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [11]:
dt_data

          id       data  vaga_disponivel    preco
0        857 2016-01-04            False     None
1        857 2016-01-05            False     None
2        857 2016-01-06            False     None
3        857 2016-01-07            False     None
4        857 2016-01-08            False     None
...      ...        ...              ...      ...
364995  3279 2016-12-29             True  $140.00
364996  3279 2016-12-30             True  $140.00
364997  3279 2016-12-31             True  $140.00
364998  3279 2017-01-01             True  $140.00
364999  3279 2017-01-02            False     None

[365000 rows x 4 columns]

In [12]:
dt_data[dt_data['vaga_disponivel'] == True]

          id       data  vaga_disponivel    preco
56       857 2016-02-29             True  $120.00
57       857 2016-03-01             True  $120.00
58       857 2016-03-02             True  $120.00
59       857 2016-03-03             True  $120.00
60       857 2016-03-04             True  $120.00
...      ...        ...              ...      ...
364994  3279 2016-12-28             True  $140.00
364995  3279 2016-12-29             True  $140.00
364996  3279 2016-12-30             True  $140.00
364997  3279 2016-12-31             True  $140.00
364998  3279 2017-01-01             True  $140.00

[270547 rows x 4 columns]

In [13]:
dt_data['preco'].isnull().sum()

np.int64(94453)

In [14]:
# Preenche valores nulos com uma string vazia para evitar o erro de atributo
dt_data.fillna({'preco': '0.0'}, inplace=True)

# Remove o símbolo '$', vírgulas e espaços em branco da coluna 'preco'
dt_data['preco'] = dt_data['preco'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

# Converte a coluna 'preco' para o tipo float64
dt_data['preco'] = dt_data['preco'].astype(np.float64)

# Exibe informações sobre o DataFrame para verificar os tipos de dados
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            365000 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1)
memory usage: 11.5 MB

In [15]:
dt_data['preco'].isnull().sum()

np.int64(0)

#Exercício: trabalhando em outros contextos

Voltemos a pôr em prática tudo o que aprendemos durante as aulas. Disponibilizei novamente os 2 novos conjuntos de dados para download abaixo:

*  Projeto desafio1: vendas online - dados_vendas_clientes.json;

*  Projeto desafio 2: administração de condomínios - dados_locacao_imoveis.json.

Lembrando: Esses dois projetos de tratamento foram construídos durante o andamento do curso. Portanto, considere os desenvolvimentos anteriores para a realização dessa etapa final.

##Etapa 4

*  Projeto desafio 1: vendas online

Nas etapas anteriores, já trabalhamos com vários tipos de dados, agora podemos trabalhar com os dados de tempo.

Na coluna `Data de venda`, temos datas em formato 'dia/mês/ano' (`dd/mm/AAAA`). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 1, vou deixar abaixo o texto da situação para facilitar o encontro da informação:

>O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

*  Projeto desafio 2: administração de condomínios

Assim como no projeto desafio 1, trabalhamos com todas as colunas exceto as que envolvem datas.

Nas colunas `datas_de_pagamento` e `datas_combinadas_pagamento`, temos datas em formato 'dia/mês/ano' (`dd/mm/AAAA`). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 2, vou deixar abaixo o texto da situação para facilitar o encontro da informação:

>A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece. Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio fictício de alguns moradores.

In [20]:
import pandas as pd
import numpy as np
import io

def carregar_dados(url: str, chave: str, coluna_valor: str, prefixo_remover: list[str] = None) -> pd.DataFrame:
    """
    Lê um JSON de uma URL, normaliza os dados, explode listas e limpa a coluna de valores monetários.

    Args:
        url (str): Link do arquivo JSON.
        chave (str): Nome da chave principal do JSON (ex.: 'dados_vendas').
        coluna_valor (str): Nome da coluna que contém os valores monetários.
        prefixo_remover (list[str], opcional): Strings a serem removidas antes de converter em float.

    Returns:
        pd.DataFrame: DataFrame normalizado e com a coluna de valores em float.
    """
    # Carrega e normaliza
    dados = pd.read_json(io.StringIO(pd.read_json(url).to_json()))
    dados = pd.json_normalize(dados[chave])

    # Explode as colunas de listas
    colunas = list(dados.columns)
    dados = dados.explode(colunas[1:]).reset_index(drop=True)

    # Limpeza da coluna de valores
    if prefixo_remover:
        for item in prefixo_remover:
            dados[coluna_valor] = dados[coluna_valor].str.replace(item, '', regex=False)

    dados[coluna_valor] = dados[coluna_valor].str.replace(',', '.', regex=False).str.strip()
    dados[coluna_valor] = dados[coluna_valor].astype(np.float64)

    return dados


url_vendas = "https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/dados_vendas_clientes.json"
url_locacao = "https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/dados_locacao_imoveis.json"

dados_vendas = carregar_dados(url_vendas, chave="dados_vendas", coluna_valor="Valor da compra", prefixo_remover=["R$ "])
dados_locacao = carregar_dados(url_locacao, chave="dados_locacao", coluna_valor="valor_aluguel", prefixo_remover=["$", " reais"])

print(dados_vendas.head())
print(dados_locacao.head())

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ANA _LUCIA 321           836.50
1    06/06/2022  DieGO ARMANDIU 210           573.33
2    06/06/2022  DieGO ARMANDIU 210           392.80
3    06/06/2022  DieGO ARMANDIU 210           512.34
4    07/06/2022  Isabely JOanes 738           825.31
      apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022         1000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022         2500.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022         1100.0
3  A102 (blocoAP)                 02/07/2022         06/07/2022         2600.0
4  B201 (blocoAP)                 03/06/2022         07/06/2022         1200.0

In [21]:
dados_vendas['Cliente'] = dados_vendas['Cliente'].str.lower()
dados_vendas['Cliente'] = dados_vendas['Cliente'].str.replace(r'[^a-z]', ' ', regex=True)
dados_locacao['apartamento'] = dados_locacao['apartamento'].str.replace('(blocoAP)', '', regex=False)

In [22]:
dados_vendas['Data de venda'] = pd.to_datetime(dados_vendas['Data de venda'], format='%d/%m/%Y')

total_compras = dados_vendas.groupby(['Cliente'])['Valor da compra'].sum()

total_compras

Cliente
 ana  lucia            836.50
diego armandiu        1478.47
isabely joanes        2329.30
jo o gabriel           386.34
julya meireles        1643.74
maria julia           2086.65
paulo castro           899.16
pedro pasco            311.15
thiago fritzz          885.24
Name: Valor da compra, dtype: float64

In [23]:
dados_locacao['datas_combinadas_pagamento'] = pd.to_datetime(dados_locacao['datas_combinadas_pagamento'], format='%d/%m/%Y')
dados_locacao['datas_de_pagamento'] = pd.to_datetime(dados_locacao['datas_de_pagamento'], format='%d/%m/%Y')
dados_locacao['atraso'] = (dados_locacao['datas_de_pagamento'] - dados_locacao['datas_combinadas_pagamento']).dt.days

media_atraso = dados_locacao.groupby(['apartamento'])['atraso'].mean()

media_atraso

apartamento
A101     3.0
A102     2.0
B201     2.0
B202     2.0
C301     4.5
C302     4.0
D401     1.0
D402     4.0
E501     0.5
E502     4.0
F601     4.0
F602     1.5
G701     6.5
G702     2.0
H801     2.0
Name: atraso, dtype: float64